INSERT INTO youmiteru_backend.genre(name) values ('Shoujo');
INSERT INTO youmiteru_backend.genre(name) values ('Josei');
INSERT INTO youmiteru_backend.genre(name) values ('Shounen');
INSERT INTO youmiteru_backend.genre(name) values ('Seinen');
INSERT INTO youmiteru_backend.genre(name) values ('Apocalyptic');
INSERT INTO youmiteru_backend.genre(name) values ('Madness');
INSERT INTO youmiteru_backend.genre(name) values ('Biopunk');
INSERT INTO youmiteru_backend.genre(name) values ('Action');
INSERT INTO youmiteru_backend.genre(name) values ('Martial Arts');
INSERT INTO youmiteru_backend.genre(name) values ('Vampires');
INSERT INTO youmiteru_backend.genre(name) values ('Military');
INSERT INTO youmiteru_backend.genre(name) values ('Harem');
INSERT INTO youmiteru_backend.genre(name) values ('Demons');
INSERT INTO youmiteru_backend.genre(name) values ('Detective');
INSERT INTO youmiteru_backend.genre(name) values ('Dobutsu');
INSERT INTO youmiteru_backend.genre(name) values ('Drama');
INSERT INTO youmiteru_backend.genre(name) values ('Games');
INSERT INTO youmiteru_backend.genre(name) values ('Idols');
INSERT INTO youmiteru_backend.genre(name) values ('Ikebukuro');
INSERT INTO youmiteru_backend.genre(name) values ('Isekai');
INSERT INTO youmiteru_backend.genre(name) values ('Historical');
INSERT INTO youmiteru_backend.genre(name) values ('Kaito');
INSERT INTO youmiteru_backend.genre(name) values ('Cyberpunk');
INSERT INTO youmiteru_backend.genre(name) values ('Comedy');
INSERT INTO youmiteru_backend.genre(name) values ('Space Opera');
INSERT INTO youmiteru_backend.genre(name) values ('Space');
INSERT INTO youmiteru_backend.genre(name) values ('Magic');
INSERT INTO youmiteru_backend.genre(name) values ('Mahou Shoujo');
INSERT INTO youmiteru_backend.genre(name) values ('Machines');
INSERT INTO youmiteru_backend.genre(name) values ('Mecha');
INSERT INTO youmiteru_backend.genre(name) values ('Mystery');
INSERT INTO youmiteru_backend.genre(name) values ('Moe');
INSERT INTO youmiteru_backend.genre(name) values ('Music');
INSERT INTO youmiteru_backend.genre(name) values ('Soap Opera');
INSERT INTO youmiteru_backend.genre(name) values ('Otaku');
INSERT INTO youmiteru_backend.genre(name) values ('Parapsychology');
INSERT INTO youmiteru_backend.genre(name) values ('Parody');
INSERT INTO youmiteru_backend.genre(name) values ('Steampunk');
INSERT INTO youmiteru_backend.genre(name) values ('Everyday Life');
INSERT INTO youmiteru_backend.genre(name) values ('Police Action');
INSERT INTO youmiteru_backend.genre(name) values ('Police');
INSERT INTO youmiteru_backend.genre(name) values ('Post-apocalyptic');
INSERT INTO youmiteru_backend.genre(name) values ('Adventure');
INSERT INTO youmiteru_backend.genre(name) values ('Psychological');
INSERT INTO youmiteru_backend.genre(name) values ('Psychological Thriller');
INSERT INTO youmiteru_backend.genre(name) values ('Reverse Harem');
INSERT INTO youmiteru_backend.genre(name) values ('Romance');
INSERT INTO youmiteru_backend.genre(name) values ('Samurai');
INSERT INTO youmiteru_backend.genre(name) values ('Samurai Action');
INSERT INTO youmiteru_backend.genre(name) values ('Supernatural');
INSERT INTO youmiteru_backend.genre(name) values ('Shoujo-ai');
INSERT INTO youmiteru_backend.genre(name) values ('Shounen-ai');
INSERT INTO youmiteru_backend.genre(name) values ('Fairy Tale');
INSERT INTO youmiteru_backend.genre(name) values ('Spokon');
INSERT INTO youmiteru_backend.genre(name) values ('Sentai');
INSERT INTO youmiteru_backend.genre(name) values ('Tokusatsu');
INSERT INTO youmiteru_backend.genre(name) values ('Thriller');
INSERT INTO youmiteru_backend.genre(name) values ('Horror');
INSERT INTO youmiteru_backend.genre(name) values ('Science Fiction');
INSERT INTO youmiteru_backend.genre(name) values ('Fantasy');
INSERT INTO youmiteru_backend.genre(name) values ('School');
INSERT INTO youmiteru_backend.genre(name) values ('School Detective');
INSERT INTO youmiteru_backend.genre(name) values ('Action');